name: kivicare_patient
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.7.2+18

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #Commons
  nb_utils: ^7.1.4
  google_fonts: ^6.2.1
  html: ^0.15.6
  http: ^1.4.0
  intl: ^0.20.2
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.1
  flutter_vector_icons: ^2.0.0
  lottie: ^3.3.1
  flutter_svg: ^2.1.0
  flutter_svg_provider: ^1.0.7
  stream_transform: ^2.1.1
  flutter_local_notifications: ^19.2.1
  carousel_slider: ^5.0.0
  flutter_spinkit: ^5.2.1
  responsive_navigation_bar: ^5.0.2
  date_picker_timeline: ^1.2.7

  #firebase
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  firebase_crashlytics: ^4.3.6
  firebase_messaging: ^15.2.6

  # SOCIAL LOGIN
  the_apple_sign_in: ^1.1.1
  google_sign_in: ^6.3.0
  googleapis: ^14.0.0
  googleapis_auth: ^2.0.0
  extension_google_sign_in_as_googleapis_auth: ^2.0.13
  permission_handler: ^12.0.0+1

  # State Management
  get: ^4.7.2

  #Storage
  get_storage: ^2.1.1
  path: ^1.9.1

  #PhotoViewGallery
  photo_view: ^0.15.0

  #Pickers
  file_picker: ^10.1.9
  image_picker: ^1.1.2
  country_picker: ^2.0.27

  # Google Map
  google_maps_flutter: ^2.12.2
  geolocator: ^14.0.1
  geocoding: ^4.0.0

  # Payment
  flutter_stripe: ^11.5.0
  razorpay_flutter: ^1.4.0
  phonepe_payment_sdk: ^2.0.3
  flutterwave_standard:
    git:
      url: https://github.com/iqonic-design/flutterwave_standard.git
      ref: main

  flutter_paypal_checkout:
    git:
      url: https://github.com/iqonic-design/flutter_paypal_checkout.git
      ref: main
  
  cinetpay:
    git:
      url: https://github.com/iqonic-design/cinetpay.git
      ref: main
      
  flutter_paystack:
    git:
      url: https://github.com/iqonic-design/flutter_paystack.git
      ref: 1.5.0
 
  midpay:
    git:
      url: https://github.com/iqonic-design/midpay.git
      ref: main
  flutter_localizations:
    sdk: flutter
  percent_indicator: ^4.2.5

  uuid: any
  crypto: any
  path_provider: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/flags/
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - assets/icons/navigation/
    - assets/icons/social_media/
    - assets/images/walkthrough_images/
    - assets/icons/upi_payment/